{!! Html::script('/bower/jquery/dist/jquery.min.js') !!}
{!! Html::script('/bower/bootstrap/dist/js/bootstrap.min.js') !!}
{!! Html::script('/bower/jquery-ui/jquery-ui.min.js') !!}
{!! Html::script('/bower/jquery-validation/dist/jquery.validate.min.js') !!}
{!! Html::script('/bower/fastclick/lib/fastclick.js') !!}
{!! Html::script('/bower/nprogress/nprogress.js') !!}
{!! Html::script('/bower/chart.js/dist/Chart.min.js') !!}
{!! Html::script('/bower/bernii/gauge.js/dist/gauge.min.js') !!}
{!! Html::script('/bower/iCheck/icheck.min.js') !!}
{!! Html::script('/bower/bootstrap-progressbar/bootstrap-progressbar.min.js') !!}
{!! Html::script('/bower/Flot/jquery.flot.js') !!}
{!! Html::script('/bower/Flot/jquery.flot.pie.js') !!}
{!! Html::script('/bower/Flot/jquery.flot.time.js') !!}
{!! Html::script('/bower/Flot/jquery.flot.stack.js') !!}
{!! Html::script('/bower/Flot/jquery.flot.resize.js') !!}
{!! Html::script('/bower/flot.orderbars/js/jquery.flot.orderBars.js') !!}
{!! Html::script('/bower/flot-spline/js/jquery.flot.spline.min.js') !!}
{!! Html::script('/bower/flot.curvedlines/curvedLines.js') !!}
{!! Html::script('/bower/chosen/chosen.jquery.js') !!}
{!! Html::script('/bower/browser-js/browser.min.js') !!}
{!! Html::script('/bower/react/react.min.js') !!}
{!! Html::script('/bower/react/react-dom.min.js') !!}
{!! Html::script('/bower/react/react-dom-server.min.js') !!}
{!! Html::script('/bower/react/react-with-addons.min.js') !!}
{!! Html::script('js/admin_message.js', ['type' => 'text/babel']) !!}
{!! Html::script('js/custom.min.js') !!}
{!! Html::script('js/index_admin.js') !!}
{!! Html::script('js/all.js') !!}
{!! Html::script('js/validate.js') !!}
